export const hebrewCopy = {
  login: {
    title: "ברוכים השבים",
    emailLabel: "אימייל",
    passwordLabel: "סיסמה",
    submitLabel: "כניסה",
    createAccountLabel: "יצירת חשבון",
  },
  register: {
    title: "יצירת חשבון",
    emailLabel: "אימייל",
    passwordLabel: "סיסמה",
    submitLabel: "יצירת חשבון",
    haveAccountLabel: "כבר יש לכם חשבון? כניסה",
  },
  budget: {
    title: "התקציב שלי",
    addExpenseLabel: "הוספת הוצאה",
    incomeLabel: "הכנסה",
    plannedLabel: "מתוכנן",
    availableLabel: "פנוי לתכנון",
    createBudgetLabel: "הגדרת התקציב",
    emptyTitle: "עדיין אין תקציב",
    emptyDescription: "לא הצלחנו למצוא את התקציב. הגדירו אותו כדי להמשיך.",
    loadErrorTitle: "לא ניתן לטעון את התקציב",
    loadErrorDescription: "בדקו את החיבור ונסו שוב.",
    retryLabel: "ניסיון נוסף",
    overPlanLabel: "מעל לתקציב",
    unplannedLabel: "הוצאה לא מתוכננת",
    overAllocatedWarning: "התקציב המתוכנן גבוה מההכנסה.",
    editIncomeTitle: "עריכת הכנסה",
    editCategoryTitle: (name) => `עריכת התקציב: ${name}`,
    plannedAmountLabel: "סכום מתוכנן",
    editIncomeAria: (amount) => `עריכת הכנסה, כרגע ${amount}`,
    editPlanAria: "עריכת סכום מתוכנן",
    addExpenseForAria: (name) => `הוספת הוצאה: ${name}`,
    saveLabel: "שמירה",
    cancelLabel: "ביטול",
    invalidAmountError: "יש להזין סכום תקין.",
    incomeUpdatedStatus: "ההכנסה עודכנה",
    categoryUpdatedStatus: (name) => `התקציב עבור ${name} עודכן`,
    budgetCreatedStatus: "התקציב נוצר",
    saveErrorTitle: "לא ניתן לשמור את התקציב.",
    spentPreview: (spent, planned) =>
      `הוצאות של ${spent} מתוך ${planned} שתוכננו לחודש זה`,
  },
  expense: {
    amountLabel: "סכום",
    categoryLabel: "קטגוריה",
    categoryPlaceholder: "בחירת קטגוריה",
    dateLabel: "תאריך",
    noteLabel: "הערה (לא חובה)",
    saveLabel: "שמירת הוצאה",
    cancelLabel: "ביטול",
    addedStatus: "ההוצאה נוספה",
    deletedStatus: "ההוצאה נמחקה",
    saveErrorTitle: "לא ניתן לשמור את ההוצאה.",
    retryLabel: "ניסיון נוסף",
    historyTitle: "הוצאות אחרונות",
    emptyHistory: "עדיין אין הוצאות בחודש זה.",
    deleteTitle: "מחיקת הוצאה",
    deleteConfirmLabel: "מחיקה",
    deleteErrorTitle: "לא ניתן למחוק את ההוצאה.",
  },
  plan: { previousMonthLabel: "החודש הקודם", nextMonthLabel: "החודש הבא" },
  insights: {
    title: "תובנות הוצאות",
    comparisonPattern: (amount) => `לעומת ${amount} בחודש שעבר`,
    barChartTitle: "הוצאות לפי קטגוריה",
    donutChartTitle: "התפלגות הוצאות",
    lineChartTitle: "מגמת הוצאות מצטברות",
    menuLabel: "תובנות",
    backToBudgetLabel: "חזרה לתקציב",
    noComparison: "אין נתונים להשוואה",
    noComparisonDetail: (label) => `עדיין אין נתונים עבור ${label}.`,
    noSpending: (label) => `עדיין אין הוצאות עבור ${label}.`,
    totalLabel: (label) => `סך ההוצאות ב${label}`,
    loadErrorTitle: "לא ניתן לטעון את התובנות",
    loadErrorDescription: "בדקו את החיבור ונסו שוב.",
    retryLabel: "ניסיון נוסף",
    emptyTitle: "עדיין אין תקציב",
    emptyDescription: "הגדירו תקציב כדי לראות תובנות.",
    monthSelectLabel: "חודשים להשוואה",
    monthSelectSummary: (label, count) => (count > 0 ? `${label} ועוד ${count}` : label),
    maxMonthsHint: "בחרו עד 3 חודשים",
    minMonthsHint: "יש לבחור לפחות חודש אחד",
  },
  password: { show: "הצגת סיסמה", hide: "הסתרת סיסמה" },
  session: { expired: "הכניסה פגה. יש להיכנס שוב." },
  errors: {
    generic: "משהו השתבש. נסו שוב.",
    network: "אין חיבור לרשת. בדקו את החיבור ונסו שוב.",
  },
};
